// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TabRenamer2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "TabRenamer2022.31aa0a94-f50f-4fd7-abaf-d80f27259828";
        public const string Name = "TabRenamer2022";
        public const string Description = @"AutoHide Tabs Rename.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "PC-8001";
        public const string Tags = "tab, tabs, rename";
    }
}
